sudo: false
language: php

php:
  - nightly

before_install:
  - composer self-update

install:
  - composer install --prefer-dist --no-interaction --ignore-platform-reqs

script:
  - vendor/bin/phpunit --coverage-clover ./tests/coverage/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls -v